//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechShopWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.Warehouse_Device = new HashSet<Warehouse_Device>();
        }
    
        public int id { get; set; }
        public Nullable<int> IdWarehouse { get; set; }
        public Nullable<int> Price { get; set; }
        public string DeviceName { get; set; }
    
        public virtual ICollection<Warehouse_Device> Warehouse_Device { get; set; }
    }
}
