//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechShopWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public Warehouse()
        {
            this.Warehouse_Device = new HashSet<Warehouse_Device>();
        }
    
        public int Id { get; set; }
        public string NameWarehouse { get; set; }
        public string City { get; set; }
        public Nullable<int> InnerNumber { get; set; }
    
        public virtual ICollection<Warehouse_Device> Warehouse_Device { get; set; }
    }
}
