//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechShopWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_Device
    {
        public int IdWarehouse { get; set; }
        public int IdDevice { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
